Traceback (most recent call last):
  File "C:\blogs\Notebook\mysql_util.py", line 30, in insert
    self.cursor.execute(sql)
  File "C:\pythoninter\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\pythoninter\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\pythoninter\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\pythoninter\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\pythoninter\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\pythoninter\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\pythoninter\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\pythoninter\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Valuess('hlx121','hlx121','1540910419@qq.com')' at line 1")
